DROP TABLE IF EXISTS aaid_part RESTRICT;
DROP TABLE IF EXISTS idfa_part RESTRICT;

DROP TABLE IF EXISTS purchase_segment RESTRICT;

DROP TABLE IF EXISTS merged_aaid RESTRICT;
DROP TABLE IF EXISTS merged_idfa RESTRICT;


